require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.pack")

require("plugins.colorscheme")
require("plugins.completion")
require("plugins.telescope")
require("plugins.neo-tree")
require("plugins.treesitter")
require("plugins.treesitter-textobjects")
require("plugins.treesitter-context")
require("plugins.navic")
require("plugins.autopairs")
require("plugins.fugitive")
require("plugins.lazygit")
require("plugins.undotree")
require("plugins.floaterm")
require("plugins.ansible-detect")
require("plugins.ansible-indent")
require("plugins.shfmt")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.which-key")

require("lsp")
